export default function Legal() {
    const h1Class = 'text-2xl font-semibold pb-4';
    const h3Class = 'text-xl pb-1 pt-3 text-blue-400';
    const pClass = 'text-neutral-600';
    const ulClass = 'ml-6 list-disc flex flex-col gap-2';
    const olClass = 'ml-6 list-decimal flex flex-col gap-2';

    return (
        <div className='p-4 overflow-y-scroll'>
            <h1 className={h1Class}>Important Legal Considerations</h1>
            <hr />

            <h3 className={h3Class}>Terms of Service</h3>
            <p className={pClass}>
                Many sites (LinkedIn, Zillow, etc.) prohibit scraping in their ToS, which creates legal risk even if the data is "public."
                Always check a site's ToS before implementing scraping to make sure you understand the risks.
            </p>

            <h3 className={h3Class}>TCPA</h3>
            <p className={pClass}>
                The Telephone Consumer Protection Act of 1991 (TCPA) is a federal law (47 U.S.C. § 227) enacted to restrict telemarketing calls, SMS texts, and fax advertisements, particularly those using automated systems or prerecorded voices.
                When using these leads, make sure you receive express written consent prior to reaching out using automated calls, texts, emails, or fax messages.
                Manually calling or otherwise messaging leads is not prohibited by the TCPA.
            </p>

            <h3 className={h3Class}>CAN-SPAM</h3>
            <p className={pClass}>
                The Controlling the Assault of Non-Solicited Pornography and Marketing (CAN-SPAM) Act of 2003 is a U.S. law setting rules for commercial email.
                <br />Key requirements include:
            </p>

            <ul className={ulClass}>
                <li>Truthful Headers: "From," "To," and routing information must be accurate.</li>
                <li>Honest Subject Lines: The subject must reflect the content, not deceive recipients.</li>
                <li>Identify Advertisement: The message must clearly state it is an advertisement.</li>
                <li>Include Location: You must provide a valid, physical postal address.</li>
                <li>Clear Opt-Out: An easy-to-use "unsubscribe" mechanism must be included, and requests must be honored within 10 business days.</li>
            </ul>

            <h3 className={h3Class}>DNC Registry</h3>
            <p className={pClass}>
                All leads must be scrubbed against the National Do Not Call (DNC) Registry.
                Nearly every state also has its own DNC list, which should also be checked before soliciting to avoid legal consequence.
            </p>

            <h3 className={h3Class}>Data Accuracy and Fair Use</h3>
            <p className={pClass}>
                Using inaccurate scraped data to determine insurance eligibility may trigger the Fair Credit Reporting Act (FCRA), which has strict rules about consumer reports.
                Additionally, if scraped data includes protected class information (age, race, disability status), using it during underwriting or targeting could raise discrimination issues under federal and state law.
                During the underwriting process, always ensure you are only using data directly provided to you by or otherwise verified by the prospect.
            </p>

            <h3 className={h3Class}>General Best Practices</h3>
            <p className={pClass}>
                There are a multitude of additional federal and state laws and regulations relating to privacy, insurance, and marketing, including GLBA, FTC, CCPA/CPRA, FIPA, NAIC laws, and many more.
                In order to be generally compliant with the vast majority of these restrictions, the following guidelines should be strictly followed during the usage of this software:
            </p>
            <ol className={olClass}>
                <li>Only ever use the software for your own personal lead generation purposes. At no point should the software ever be used as the primary source of lead generation for any commercial enterprise, business, group, corporation, or otherwise.</li>
                <li>Do not sell leads generated by the software.</li>
                <li>Do not share leads or personal data generated by the software with anyone else.</li>
                <li>Do not store leads or personal data for extended periods of time. Implement strong data retention policies and automatic data deletion.</li>
                <li>Do not use any data generated by the software for any use beyond the initial contact and sales pitch to the prospect, such as for determining policy eligibility or during underwriting.</li>
                <li>Always remove prospect information from the lead database upon request. Additionally, a separate database of opt-outs should be maintained and scrubbed against as a part of the lead-generation process.</li>
            </ol>

            <h3 className={h3Class}>Limitation of Liability; User Responsibility for Leads and Personal Data</h3>
            <div className='flex flex-col gap-2'>
                <p className={pClass}>
                    The user acknowledges and agrees that it is solely responsible for
                    <strong> (a)</strong> its use of the software, including any insurance sales leads generated, received, processed, or acted on through the software,
                    <strong> (b)</strong> its collection, access, use, storage, disclosure, transfer, sale, solicitation, and other processing of any lead information, personal data, or other information relating to any identified or identifiable individual, and
                    <strong> (c)</strong> its compliance with all applicable laws, regulations, industry guidelines, and third-party requirements relating to privacy, data protection, consumer communications, insurance marketing, telemarketing, email marketing, recordkeeping, and data security, including all requirements regarding consent, notice, authorization, opt-out, and permitted use.
                </p>

                <p className={pClass}>
                    The user will not use the software, or any output generated by the software, in any manner that violates applicable law or infringes the rights of any person.
                    The software developer does not control, monitor, validate, or assume responsibility for user's use of any lead information or personal data, or for the legality, accuracy, quality, permissibility, or appropriateness of any contact, follow-up, solicitation, underwriting activity, marketing activity, sale, or other action taken by the user or any of its representatives using or based on the software or its output.
                </p>

                <p className={pClass}>
                    To the fullest extent permitted by law, the software developer will have no liability whatsoever, whether in contract, tort (including negligence), strict liability, statute, or otherwise, for any claim, loss, damage, penalty, fine, cost, or expense arising out of or relating to
                    <strong> (i)</strong> any user’s misuse, unauthorized access, unlawful processing, disclosure, sale, transfer, or other handling of any lead information or personal data,
                    <strong> (ii)</strong> user's failure to obtain any legally required consent, notice, or authorization,
                    <strong> (iii)</strong> user's violation of any privacy, data protection, consumer protection, insurance, telemarketing, or marketing law, rule, or regulation, or
                    <strong> (iv)</strong> any claim by a lead, consumer, regulator, insurer, producer, agency, or other third party arising from user's use of the software or any output generated by it.
                </p>
            </div>
        </div>
    );
};
